#!/usr/bin/env python3
"""Generate the offline UI study's balance data from the canonical JSON."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def expected_source() -> str:
    data = json.loads((ROOT / "data/balance.json").read_text(encoding="utf-8"))
    return "// Generated by tools/sync_prototype.py; edit data/balance.json instead.\nwindow.RADAR_BALANCE = " + json.dumps(data, indent=2) + ";\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "prototype/balance.js"
    source = expected_source()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != source:
            print("Prototype data is stale. Run python3 tools/sync_prototype.py")
            return 1
        return 0
    target.write_text(source, encoding="utf-8")
    print("Updated prototype/balance.js")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
